log:
  level: debug
  format: console
kafka:
  url: localhost:9092
  env: staging
rpcs:
  ethereum:
    full:
      - wss://hopeful-leakey:spud-chaste-trance-width-upward-harbor@ws-nd-334-593-626.p2pify.com
  optimism:
    full:
      -  wss://ws-mainnet.optimism.io
  arbitrum:
    full:
      -  wss://arb1.arbitrum.io/ws
  bsc:
    full:
      - wss://solitary-autumn-lake.bsc.quiknode.pro/5ae982d695add4572c00074294efbc338e5a4c18/
      - https://solitary-autumn-lake.bsc.quiknode.pro/5ae982d695add4572c00074294efbc338e5a4c18/